### ISSUE TITLE
Version 2017-04-16 is not working with PHP 5.6.30-0+deb8u1, needs php 7

### ISSUE THREAD

**Issue by bernhardbrunner** [real-or-random/dokuwiki-plugin-icalevents#14]
After installation, dokuwiki stops working with a blank page.

Immediate fix: delete icalevents in .../lib/plugins

Findings: 
fatal php Error in sabre functions.php
 [26-Apr-2017 11:37:46 Europe/Berlin] PHP Warning:  Unsupported declare 'strict_types' in /var/www/XXX/li
b/plugins/icalevents/vendor/sabre/uri/lib/functions.php on line 1 
 [26-Apr-2017 11:37:46 Europe/Berlin] PHP Parse error:  syntax error, unexpected ':', expecting '{' in /var/www
/XXX/lib/plugins/icalevents/vendor/sabre/uri/lib/functions.php on line 23

Reason: 
sabre library bundled with the 2017-04-16 release needs php 7 (strict mode and function return type declarations)

Fix: download and unzip previous version, which works well

**Comment by real-or-random** [comment]
Uh, that shouldn't have happened. I'll release a fix later today...

**Comment by real-or-random** [comment]
https://github.com/real-or-random/dokuwiki-plugin-icalevents/releases/tag/2017-04-26

**Comment by bernhardbrunner** [comment]
Now that was a quick fix, thanks a lot!
