### ISSUE TITLE
500 when using "from" and "to" args

### ISSUE THREAD

**Issue by martingabelmann** [real-or-random/dokuwiki-plugin-icalevents#15]
The dokuwiki page contains:
```
{{iCalEvents>[googlecalendarurl]#showAs=list&from=today&to=+7 days&sort=desc&dformat=%d.%m.%y}}
```
  
the apache log says:
  
> [Sat Jun 10 14:22:35.900582 2017] [:error] [pid 2033] [client 217.249.24.41:52858] PHP Fatal error:  Uncaught Error: Call to a member function getIterator() on null in     [wwwpath]/lib/plugins/icalevents/syntax-impl.php:218\nStack trace:\n#0   [wwwpath]/inc/parser/renderer.php(105): syntax_plugin_icalevents->render('metadata',   Object(Doku_Renderer_metadata), Array)\n#1 /[wwwpath]/inc/parserutils.php(495): Doku_Renderer-  >plugin('icalevents', Array, 5, '{{iCalEvents>ht...')\n#2 [wwwpath]/inc/parserutils.php(270):   p_render_metadata('[dokuwikipath]:...', Array)\n#3 [wwwpath]/inc/common.php(251):   p_get_metadata('[dokuwikipath]:...')\n#4 [wwwpath]/doku.php(91): pageinfo()\n#5 {main}\n  thrown in   [wwwpath]/lib/plugins/icalevents/syntax-impl.php on line 218

When I remove the `&from=today&to=+7 days` part, everything works.  
The plugin is on the newest version (installed with the dokuwiki webinterface).  
  
Thanks in advance.

**Comment by martingabelmann** [comment]
some more infos about our system:  
dokuwiki: 2017-02-19b
php: 7.0.18-0

**Comment by real-or-random** [comment]
Thanks for the bug report. 

I get the same error if the date range does not contain any events and so there is nothing to display. Can you confirm that this is also true in your case?

**Comment by martingabelmann** [comment]
Yes, that seems to be/was the case for me as well. Thanks a lot!
