### ISSUE TITLE
Support for filter according to status of event

### ISSUE THREAD

**Issue by es-ka** [real-or-random/dokuwiki-plugin-icalevents#17]
Add a parameter like `status` of type string to filter events according to their status.
E.g.: `{{iCalEvents>myCalendar.ics#status=tentative}}` to show tentative events only

**Comment by real-or-random** [comment]
The problem is that this probably needs a more expressive query language. Why allow "tentative" and not "NOT tentative" for example? On the other hand, there are only three possible values for the status property, so a boolean NOT will suffice.
 
Do you really need this feature?

**Comment by es-ka** [comment]
You are right concerning the query.
BTW, I don't need this feature at the moment. I just thought it would be nice ;-)

**Comment by real-or-random** [comment]
I see. :) I expect "status" to be a rather uncommon property for calendars in wiki pages. And even if someone uses it, the special formatting (#16) will provide basic support. So as long as noone really needs this feature, I prefer to avoid the complexity (and save the time).
