### ISSUE TITLE
Just doesn't work at all

### ISSUE THREAD

**Issue by intervisionlord** [real-or-random/dokuwiki-plugin-icalevents#20]
With local *.ics file got error:

> Error in Plugin iCalEvents: could not read media file calendar.ics.

With link:

> Error in Plugin iCalEvents: invalid iCalendar input.

**Comment by real-or-random** [comment]
Thanks for the report. Could you provide some more information?

 - What's the code you use to use the plugin?
 - DokuWiki version?
 - PHP version?
 - Is this is a public installation? If yes, can you point me to the page?

**Comment by intervisionlord** [comment]
{{iCalEvents>URL_to_ICS_File}}
DokuWiki: Release 2018-04-22b "Greebo"
PHP: 7.3.4
Private Installation

**Comment by real-or-random** [comment]
What happens if you access `dokuwiki/lib/exe/fetch.php?media=calendar.ics`? Does your browser download the file successfully?

**Comment by intervisionlord** [comment]
404

But... I have changed the calendar and link to it to https://calendar.server.url/dav/public-calendars/*calendar_hash*?export

and it is worked.
But there is another issue with formatting (i guess i need to open a new issue about it?)

**Comment by real-or-random** [comment]
Nice that you managed to get it working. For the formatting: Yes, please open a separate issue.
