### ISSUE TITLE
Feature - Locale settings

### ISSUE THREAD

**Issue by intervisionlord** [real-or-random/dokuwiki-plugin-icalevents#24]
Hello.

What are you think about implementing locale settings to display date and time on user prefered language?

Now i am using a row `setlocale(LC_ALL, "ru_RU.UTF-8");` in `syntax-impl.php`, but what if this setting could be selected via admin menu or would be defined in localization file?

**Comment by real-or-random** [comment]
I think the proper way is to set the locale 
 - on your OS
 - or if you can't do this, then in the PHP config
 - or if you can't do this, then in `conf/local.protected.php`.

So I think the proper way is to put `setlocale(LC_ALL, "ru_RU.UTF-8");` in `conf/local.protected.php`.

**Comment by intervisionlord** [comment]
There are some strange things with locales...
- i have 2 servers (Debian 8 and CentOS 6) with correct locales:
```
> locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=ru_RU.UTF-8
```

- Also i have locale settings in my php:
```
> /opt/php73/bin/php -v | grep -i built; /opt/php73/bin/php -i | grep LC_
PHP 7.3.11 (cli) (built: Oct 28 2019 17:13:30) ( NTS )
LC_ALL => ru_RU.UTF-8
LC_CTYPE => C
$_SERVER['LC_ALL'] => ru_RU.UTF-8
$_SERVER['LC_CTYPE'] => C
```
And this does not helps ;(
But anyway, modifying `conf/local.protected.php` helps, thank you.
