### ISSUE TITLE
Examples in documentation

### ISSUE THREAD

**Issue by iainhallam** [real-or-random/dokuwiki-plugin-icalevents#7]
I've been looking for plugins to evaluate, and this looks promising, but from my current connection I can't really install a test instance. Is it possible to have either a demonstration site or screenshots on the plugin page, please?

**Comment by real-or-random** [comment]
I've added two screenshots here:
https://www.dokuwiki.org/plugin:icalevents

Feel free to ask if you need more information, or if you need a particular feature.

**Comment by glensc** [comment]
@real-or-random i think you should upload the screenshots to dokuwiki not to rely on third party site to host them forever.

also you can configure not to show them inline if you wish (via `?linkonly`):
https://www.dokuwiki.org/images

**Comment by real-or-random** [comment]
Oh for some reasons I had in mind that uploads are not allowed. And I
didn't know linkonly. Feel free to change it.

**Comment by glensc** [comment]
oh, i didn't know media uploads are disabled on dokuwiki.org
