### ISSUE TITLE
Adjust timezone offset

### ISSUE THREAD

**Issue by veromary** [real-or-random/dokuwiki-plugin-icalevents#8]
I was using iCalendar, then saw the recommendation to change to iCalEvents, but my events come up shifted eleven hours earlier than they should.

I'm using wiggio.com to generate the calendar.  I'm in Australia which is roughly UTC+10 depending on daylight savings time.

An example is here: [http://providencehomeschool.org/doku.php?id=bug_squish](url)

It's especially awkward when it changes the date of the event.

**Comment by veromary** [comment]
I can see the date and time is being faithfully reproduced from the ics file:
[https://wiggio.com/cal.php?code=506648565712062504](url)

The ics doesn't seem to include any timezone info and gives dates and times in UTC.  I don't understand how iCalendar got it right.

I edited syntax.php adding in a line (giving some surrounding code for context)

```
                    if ($local) {
                        $dto = new DateTime($full);
                    }
                }
                $dto = new DateTime($full, new DateTimeZone('UTC')); // added this line
                $dt['timestamp'] = $dto->getTimestamp();
            } catch (Exception $eDate) {
                // invalid date or time
                $dt['timestamp'] = '';
                $dt['datestring'] = '';
                $dt['timestring'] = '';
                continue;
            }
```

I think I've bypassed the proper timezone code but it works for now.

**Comment by real-or-random** [comment]
It was indeed a bug. The iCalendar file indicates UTC properly. (It just does not contain a time zone identifier but UTC is indicated by the trailing `Z` after the date time.) 

Can you test the latest revision?

**Comment by glensc** [comment]
i think `Z` with no value exactly indicates UTC. [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard indicates that.

**Comment by real-or-random** [comment]
Yes yes. It's just awkward that iCalcreator doesn't translate it. Also, I thought I had testes UTC events. Anyways, should be fixed now. 

Am 24. September 2016 18:18:48 MESZ, schrieb "Elan Ruusamäe" notifications@github.com:

**Comment by veromary** [comment]
All good here.  Thanks!
